// AUTO-GENERATED SEED
import type { Employee, UserProfile, UserAccount, CurriculumItem, Course, CourseTrainee, HRRequest, CorrespondenceItem, Task, GovernorateTraining, FollowUpRecord, FollowUpNotification, Notification, AuditEntry, WeekScheduleEntry } from "./localStore";

export const SEED_EMPLOYEES: Employee[] = [
  {
    "id": "emp-1",
    "name": "أحمد محمد العلي",
    "department": "شعبة الإعداد والتدريب",
    "section": "شعبة الإعداد والتدريب",
    "position": "مدير النظام",
    "phone": "07700000001",
    "work_schedule": "daily",
    "created_at": "2026-01-01T08:00:00Z",
    "updated_at": "2026-01-01T08:00:00Z"
  },
  {
    "id": "emp-2",
    "name": "فاطمة حسن الأمير",
    "department": "إدارة التدريب",
    "section": "إدارة التدريب",
    "position": "مدير القسم",
    "phone": "07700000002",
    "work_schedule": "daily",
    "created_at": "2026-01-01T08:00:00Z",
    "updated_at": "2026-01-01T08:00:00Z"
  },
  {
    "id": "emp-3",
    "name": "خالد عبدالله السعيد",
    "department": "شعبة الإعداد والتدريب",
    "section": "شعبة الإعداد والتدريب",
    "position": "رئيس شعبة الإعداد والتدريب",
    "phone": "07700000003",
    "work_schedule": "daily",
    "created_at": "2026-01-01T08:00:00Z",
    "updated_at": "2026-01-01T08:00:00Z"
  },
  {
    "id": "emp-4",
    "name": "نورة سعد المالكي",
    "department": "شعبة المناهج",
    "section": "شعبة المناهج",
    "position": "رئيس شعبة المناهج",
    "phone": "07700000004",
    "work_schedule": "daily",
    "created_at": "2026-01-01T08:00:00Z",
    "updated_at": "2026-01-01T08:00:00Z"
  },
  {
    "id": "emp-5",
    "name": "محمد علي الزهراني",
    "department": "شعبة الإعداد والتدريب",
    "section": "شعبة الإعداد والتدريب",
    "position": "موظف موارد بشرية",
    "phone": "07700000005",
    "work_schedule": "daily",
    "created_at": "2026-01-01T08:00:00Z",
    "updated_at": "2026-01-01T08:00:00Z"
  },
  {
    "id": "emp-6",
    "name": "سارة يوسف القحطاني",
    "department": "شعبة الإعداد والتدريب",
    "section": "شعبة الإعداد والتدريب",
    "position": "موظف إعداد",
    "phone": "07700000006",
    "work_schedule": "daily",
    "created_at": "2026-01-01T08:00:00Z",
    "updated_at": "2026-01-01T08:00:00Z"
  },
  {
    "id": "emp-7",
    "name": "عبدالرحمن فهد الشمري",
    "department": "شعبة الإعداد والتدريب",
    "section": "شعبة الإعداد والتدريب",
    "position": "أمين الأرشيف",
    "phone": "07700000007",
    "work_schedule": "daily",
    "created_at": "2026-01-01T08:00:00Z",
    "updated_at": "2026-01-01T08:00:00Z"
  },
  {
    "id": "emp-8",
    "name": "هند ماجد العتيبي",
    "department": "شعبة الإعداد والتدريب",
    "section": "شعبة الإعداد والتدريب",
    "position": "منسق تنفيذ تدريبي",
    "phone": "07700000008",
    "work_schedule": "daily",
    "created_at": "2026-01-01T08:00:00Z",
    "updated_at": "2026-01-01T08:00:00Z"
  },
  {
    "id": "emp-9",
    "name": "علي حسين الخفاجي",
    "department": "شعبة الإعداد والتدريب",
    "section": "شعبة الإعداد والتدريب",
    "position": "محرر تقارير",
    "phone": "07700000009",
    "work_schedule": "daily",
    "created_at": "2026-01-01T08:00:00Z",
    "updated_at": "2026-01-01T08:00:00Z"
  },
  {
    "id": "emp-10",
    "name": "زينب كريم الموسوي",
    "department": "شعبة المناهج",
    "section": "شعبة المناهج",
    "position": "كاتب مناهج",
    "phone": "07700000010",
    "work_schedule": "daily",
    "created_at": "2026-01-01T08:00:00Z",
    "updated_at": "2026-01-01T08:00:00Z"
  },
  {
    "id": "emp-11",
    "name": "ليث جاسم العبيدي",
    "department": "شعبة المناهج",
    "section": "شعبة المناهج",
    "position": "مصمم عروض",
    "phone": "07700000011",
    "work_schedule": "daily",
    "created_at": "2026-01-01T08:00:00Z",
    "updated_at": "2026-01-01T08:00:00Z"
  },
  {
    "id": "emp-12",
    "name": "مريم عادل الحسيني",
    "department": "شعبة المناهج",
    "section": "شعبة المناهج",
    "position": "منسق خطة تدريبية",
    "phone": "07700000012",
    "work_schedule": "daily",
    "created_at": "2026-01-01T08:00:00Z",
    "updated_at": "2026-01-01T08:00:00Z"
  },
  {
    "id": "emp-13",
    "name": "حسن قاسم الربيعي",
    "department": "شعبة المناهج",
    "section": "شعبة المناهج",
    "position": "مقيّم",
    "phone": "07700000013",
    "work_schedule": "daily",
    "created_at": "2026-01-01T08:00:00Z",
    "updated_at": "2026-01-01T08:00:00Z"
  },
  {
    "id": "emp-14",
    "name": "أمل ناصر الجبوري",
    "department": "شعبة المناهج",
    "section": "شعبة المناهج",
    "position": "ضابط متابعة",
    "phone": "07700000014",
    "work_schedule": "daily",
    "created_at": "2026-01-01T08:00:00Z",
    "updated_at": "2026-01-01T08:00:00Z"
  }
];
export const SEED_PROFILES: UserProfile[] = [
  {
    "id": "emp-1",
    "name": "أحمد محمد العلي",
    "department": "شعبة الإعداد والتدريب",
    "section": "شعبة الإعداد والتدريب",
    "position": "مدير النظام",
    "phone": "07700000001",
    "roles": [
      "admin",
      "super_user"
    ]
  },
  {
    "id": "emp-2",
    "name": "فاطمة حسن الأمير",
    "department": "إدارة التدريب",
    "section": "إدارة التدريب",
    "position": "مدير القسم",
    "phone": "07700000002",
    "roles": [
      "dept_manager",
      "training_admin"
    ]
  },
  {
    "id": "emp-3",
    "name": "خالد عبدالله السعيد",
    "department": "شعبة الإعداد والتدريب",
    "section": "شعبة الإعداد والتدريب",
    "position": "رئيس شعبة الإعداد والتدريب",
    "phone": "07700000003",
    "roles": [
      "unit_head"
    ]
  },
  {
    "id": "emp-4",
    "name": "نورة سعد المالكي",
    "department": "شعبة المناهج",
    "section": "شعبة المناهج",
    "position": "رئيس شعبة المناهج",
    "phone": "07700000004",
    "roles": [
      "unit_head"
    ]
  },
  {
    "id": "emp-5",
    "name": "محمد علي الزهراني",
    "department": "شعبة الإعداد والتدريب",
    "section": "شعبة الإعداد والتدريب",
    "position": "موظف موارد بشرية",
    "phone": "07700000005",
    "roles": [
      "individual"
    ]
  },
  {
    "id": "emp-6",
    "name": "سارة يوسف القحطاني",
    "department": "شعبة الإعداد والتدريب",
    "section": "شعبة الإعداد والتدريب",
    "position": "موظف إعداد",
    "phone": "07700000006",
    "roles": [
      "individual"
    ]
  },
  {
    "id": "emp-7",
    "name": "عبدالرحمن فهد الشمري",
    "department": "شعبة الإعداد والتدريب",
    "section": "شعبة الإعداد والتدريب",
    "position": "أمين الأرشيف",
    "phone": "07700000007",
    "roles": [
      "individual"
    ]
  },
  {
    "id": "emp-8",
    "name": "هند ماجد العتيبي",
    "department": "شعبة الإعداد والتدريب",
    "section": "شعبة الإعداد والتدريب",
    "position": "منسق تنفيذ تدريبي",
    "phone": "07700000008",
    "roles": [
      "individual"
    ]
  },
  {
    "id": "emp-9",
    "name": "علي حسين الخفاجي",
    "department": "شعبة الإعداد والتدريب",
    "section": "شعبة الإعداد والتدريب",
    "position": "محرر تقارير",
    "phone": "07700000009",
    "roles": [
      "individual"
    ]
  },
  {
    "id": "emp-10",
    "name": "زينب كريم الموسوي",
    "department": "شعبة المناهج",
    "section": "شعبة المناهج",
    "position": "كاتب مناهج",
    "phone": "07700000010",
    "roles": [
      "individual"
    ]
  },
  {
    "id": "emp-11",
    "name": "ليث جاسم العبيدي",
    "department": "شعبة المناهج",
    "section": "شعبة المناهج",
    "position": "مصمم عروض",
    "phone": "07700000011",
    "roles": [
      "individual"
    ]
  },
  {
    "id": "emp-12",
    "name": "مريم عادل الحسيني",
    "department": "شعبة المناهج",
    "section": "شعبة المناهج",
    "position": "منسق خطة تدريبية",
    "phone": "07700000012",
    "roles": [
      "individual"
    ]
  },
  {
    "id": "emp-13",
    "name": "حسن قاسم الربيعي",
    "department": "شعبة المناهج",
    "section": "شعبة المناهج",
    "position": "مقيّم",
    "phone": "07700000013",
    "roles": [
      "individual"
    ]
  },
  {
    "id": "emp-14",
    "name": "أمل ناصر الجبوري",
    "department": "شعبة المناهج",
    "section": "شعبة المناهج",
    "position": "ضابط متابعة",
    "phone": "07700000014",
    "roles": [
      "individual"
    ]
  }
];
export const SEED_USER_ACCOUNTS: UserAccount[] = [
  {
    "email": "admin@tadreeb.iq",
    "password": "admin123",
    "profile": {
      "id": "emp-1",
      "name": "أحمد محمد العلي",
      "department": "شعبة الإعداد والتدريب",
      "section": "شعبة الإعداد والتدريب",
      "position": "مدير النظام",
      "phone": "07700000001",
      "roles": [
        "admin",
        "super_user"
      ]
    }
  },
  {
    "email": "manager@tadreeb.iq",
    "password": "manager123",
    "profile": {
      "id": "emp-2",
      "name": "فاطمة حسن الأمير",
      "department": "إدارة التدريب",
      "section": "إدارة التدريب",
      "position": "مدير القسم",
      "phone": "07700000002",
      "roles": [
        "dept_manager",
        "training_admin"
      ]
    }
  },
  {
    "email": "prep@tadreeb.iq",
    "password": "prep123",
    "profile": {
      "id": "emp-3",
      "name": "خالد عبدالله السعيد",
      "department": "شعبة الإعداد والتدريب",
      "section": "شعبة الإعداد والتدريب",
      "position": "رئيس شعبة الإعداد والتدريب",
      "phone": "07700000003",
      "roles": [
        "unit_head"
      ]
    }
  },
  {
    "email": "curriculum@tadreeb.iq",
    "password": "curr123",
    "profile": {
      "id": "emp-4",
      "name": "نورة سعد المالكي",
      "department": "شعبة المناهج",
      "section": "شعبة المناهج",
      "position": "رئيس شعبة المناهج",
      "phone": "07700000004",
      "roles": [
        "unit_head"
      ]
    }
  },
  {
    "email": "hr1@tadreeb.iq",
    "password": "user123",
    "profile": {
      "id": "emp-5",
      "name": "محمد علي الزهراني",
      "department": "شعبة الإعداد والتدريب",
      "section": "شعبة الإعداد والتدريب",
      "position": "موظف موارد بشرية",
      "phone": "07700000005",
      "roles": [
        "individual"
      ]
    }
  },
  {
    "email": "prep1@tadreeb.iq",
    "password": "user123",
    "profile": {
      "id": "emp-6",
      "name": "سارة يوسف القحطاني",
      "department": "شعبة الإعداد والتدريب",
      "section": "شعبة الإعداد والتدريب",
      "position": "موظف إعداد",
      "phone": "07700000006",
      "roles": [
        "individual"
      ]
    }
  },
  {
    "email": "archive1@tadreeb.iq",
    "password": "user123",
    "profile": {
      "id": "emp-7",
      "name": "عبدالرحمن فهد الشمري",
      "department": "شعبة الإعداد والتدريب",
      "section": "شعبة الإعداد والتدريب",
      "position": "أمين الأرشيف",
      "phone": "07700000007",
      "roles": [
        "individual"
      ]
    }
  },
  {
    "email": "exec1@tadreeb.iq",
    "password": "user123",
    "profile": {
      "id": "emp-8",
      "name": "هند ماجد العتيبي",
      "department": "شعبة الإعداد والتدريب",
      "section": "شعبة الإعداد والتدريب",
      "position": "منسق تنفيذ تدريبي",
      "phone": "07700000008",
      "roles": [
        "individual"
      ]
    }
  },
  {
    "email": "reports1@tadreeb.iq",
    "password": "user123",
    "profile": {
      "id": "emp-9",
      "name": "علي حسين الخفاجي",
      "department": "شعبة الإعداد والتدريب",
      "section": "شعبة الإعداد والتدريب",
      "position": "محرر تقارير",
      "phone": "07700000009",
      "roles": [
        "individual"
      ]
    }
  },
  {
    "email": "cur1@tadreeb.iq",
    "password": "user123",
    "profile": {
      "id": "emp-10",
      "name": "زينب كريم الموسوي",
      "department": "شعبة المناهج",
      "section": "شعبة المناهج",
      "position": "كاتب مناهج",
      "phone": "07700000010",
      "roles": [
        "individual"
      ]
    }
  },
  {
    "email": "pres1@tadreeb.iq",
    "password": "user123",
    "profile": {
      "id": "emp-11",
      "name": "ليث جاسم العبيدي",
      "department": "شعبة المناهج",
      "section": "شعبة المناهج",
      "position": "مصمم عروض",
      "phone": "07700000011",
      "roles": [
        "individual"
      ]
    }
  },
  {
    "email": "plan1@tadreeb.iq",
    "password": "user123",
    "profile": {
      "id": "emp-12",
      "name": "مريم عادل الحسيني",
      "department": "شعبة المناهج",
      "section": "شعبة المناهج",
      "position": "منسق خطة تدريبية",
      "phone": "07700000012",
      "roles": [
        "individual"
      ]
    }
  },
  {
    "email": "eval1@tadreeb.iq",
    "password": "user123",
    "profile": {
      "id": "emp-13",
      "name": "حسن قاسم الربيعي",
      "department": "شعبة المناهج",
      "section": "شعبة المناهج",
      "position": "مقيّم",
      "phone": "07700000013",
      "roles": [
        "individual"
      ]
    }
  },
  {
    "email": "fu1@tadreeb.iq",
    "password": "user123",
    "profile": {
      "id": "emp-14",
      "name": "أمل ناصر الجبوري",
      "department": "شعبة المناهج",
      "section": "شعبة المناهج",
      "position": "ضابط متابعة",
      "phone": "07700000014",
      "roles": [
        "individual"
      ]
    }
  }
];
export const SEED_CURRICULUM: CurriculumItem[] = [
  {
    "id": "cur-1",
    "title": "منهج إدارة المشاريع الاحترافية",
    "goals": "الهدف من منهج إدارة المشاريع الاحترافية هو رفع كفاءة المتدربين",
    "target_audience": "مدراء المشاريع",
    "count": 25,
    "training_style": "ورشة عمل",
    "type": "developmental",
    "status": "applied",
    "report_uploaded": true,
    "presentation_uploaded": true,
    "created_by": "emp-4",
    "created_at": "2026-01-10T08:00:00Z",
    "updated_at": "2026-02-15T08:00:00Z",
    "printed": true,
    "form_type": "new",
    "ppt_type": "new",
    "executor_type": "internal",
    "executor_name": "أحمد محمد العلي",
    "hours": 40,
    "applied": true,
    "location": "قاعة التدريب الرئيسية",
    "trainer_name": "أحمد محمد العلي",
    "audience_count": 25,
    "audit_status": "done",
    "file_url": "",
    "file_type": "pdf",
    "hard_copy_printed": true,
    "current_stage": "done",
    "assigned_to": "emp-10",
    "handed_over_by": null,
    "handed_over_at": null
  },
  {
    "id": "cur-2",
    "title": "منهج الأمن السيبراني المتقدم",
    "goals": "الهدف من منهج الأمن السيبراني المتقدم هو رفع كفاءة المتدربين",
    "target_audience": "موظفو تقنية المعلومات",
    "count": 30,
    "training_style": "محاضرة",
    "type": "specialized",
    "status": "applied",
    "report_uploaded": false,
    "presentation_uploaded": true,
    "created_by": "emp-4",
    "created_at": "2026-01-10T08:00:00Z",
    "updated_at": "2026-02-15T08:00:00Z",
    "printed": false,
    "form_type": "new",
    "ppt_type": "new",
    "executor_type": "internal",
    "executor_name": "محمد علي الزهراني",
    "hours": 24,
    "applied": true,
    "location": "قاعة التدريب الرئيسية",
    "trainer_name": "محمد علي الزهراني",
    "audience_count": 30,
    "audit_status": "in_progress",
    "file_url": "",
    "file_type": "",
    "hard_copy_printed": false,
    "current_stage": "auditing",
    "assigned_to": "emp-10",
    "handed_over_by": null,
    "handed_over_at": null
  },
  {
    "id": "cur-3",
    "title": "منهج القيادة التحويلية",
    "goals": "الهدف من منهج القيادة التحويلية هو رفع كفاءة المتدربين",
    "target_audience": "رؤساء الأقسام",
    "count": 15,
    "training_style": "تدريب تفاعلي",
    "type": "developmental",
    "status": "not_applied",
    "report_uploaded": false,
    "presentation_uploaded": false,
    "created_by": "emp-4",
    "created_at": "2026-01-10T08:00:00Z",
    "updated_at": "2026-02-15T08:00:00Z",
    "printed": false,
    "form_type": "new",
    "ppt_type": "new",
    "executor_type": "internal",
    "executor_name": "—",
    "hours": 20,
    "applied": false,
    "location": "",
    "trainer_name": "",
    "audience_count": 0,
    "audit_status": "not_started",
    "file_url": "",
    "file_type": "",
    "hard_copy_printed": false,
    "current_stage": "writing",
    "assigned_to": "emp-10",
    "handed_over_by": null,
    "handed_over_at": null
  },
  {
    "id": "cur-4",
    "title": "منهج تحليل البيانات وذكاء الأعمال",
    "goals": "الهدف من منهج تحليل البيانات وذكاء الأعمال هو رفع كفاءة المتدربين",
    "target_audience": "المحللون",
    "count": 20,
    "training_style": "ورشة عملية",
    "type": "specialized",
    "status": "applied",
    "report_uploaded": true,
    "presentation_uploaded": true,
    "created_by": "emp-4",
    "created_at": "2026-01-10T08:00:00Z",
    "updated_at": "2026-02-15T08:00:00Z",
    "printed": true,
    "form_type": "new",
    "ppt_type": "new",
    "executor_type": "external",
    "executor_name": "خبير بيانات",
    "hours": 32,
    "applied": true,
    "location": "قاعة التدريب الرئيسية",
    "trainer_name": "خبير بيانات",
    "audience_count": 20,
    "audit_status": "done",
    "file_url": "",
    "file_type": "pdf",
    "hard_copy_printed": true,
    "current_stage": "done",
    "assigned_to": "emp-10",
    "handed_over_by": null,
    "handed_over_at": null
  },
  {
    "id": "cur-5",
    "title": "منهج مهارات التواصل المؤسسي",
    "goals": "الهدف من منهج مهارات التواصل المؤسسي هو رفع كفاءة المتدربين",
    "target_audience": "جميع الموظفين",
    "count": 40,
    "training_style": "محاضرة تفاعلية",
    "type": "developmental",
    "status": "applied",
    "report_uploaded": true,
    "presentation_uploaded": true,
    "created_by": "emp-4",
    "created_at": "2026-01-10T08:00:00Z",
    "updated_at": "2026-02-15T08:00:00Z",
    "printed": true,
    "form_type": "new",
    "ppt_type": "new",
    "executor_type": "internal",
    "executor_name": "فاطمة حسن الأمير",
    "hours": 16,
    "applied": true,
    "location": "قاعة التدريب الرئيسية",
    "trainer_name": "فاطمة حسن الأمير",
    "audience_count": 40,
    "audit_status": "done",
    "file_url": "",
    "file_type": "pdf",
    "hard_copy_printed": true,
    "current_stage": "done",
    "assigned_to": "emp-10",
    "handed_over_by": null,
    "handed_over_at": null
  },
  {
    "id": "cur-6",
    "title": "منهج إعداد التقارير الإدارية",
    "goals": "الهدف من منهج إعداد التقارير الإدارية هو رفع كفاءة المتدربين",
    "target_audience": "الموظفون الإداريون",
    "count": 25,
    "training_style": "ورشة كتابة",
    "type": "developmental",
    "status": "not_applied",
    "report_uploaded": false,
    "presentation_uploaded": true,
    "created_by": "emp-4",
    "created_at": "2026-01-10T08:00:00Z",
    "updated_at": "2026-02-15T08:00:00Z",
    "printed": false,
    "form_type": "new",
    "ppt_type": "new",
    "executor_type": "internal",
    "executor_name": "—",
    "hours": 12,
    "applied": false,
    "location": "",
    "trainer_name": "",
    "audience_count": 0,
    "audit_status": "in_progress",
    "file_url": "",
    "file_type": "",
    "hard_copy_printed": false,
    "current_stage": "new_ppt",
    "assigned_to": "emp-11",
    "handed_over_by": null,
    "handed_over_at": null
  },
  {
    "id": "cur-7",
    "title": "منهج الإدارة الإلكترونية / Office",
    "goals": "الهدف من منهج الإدارة الإلكترونية / Office هو رفع كفاءة المتدربين",
    "target_audience": "كل الموظفين",
    "count": 50,
    "training_style": "تطبيق عملي",
    "type": "specialized",
    "status": "applied",
    "report_uploaded": true,
    "presentation_uploaded": true,
    "created_by": "emp-4",
    "created_at": "2026-01-10T08:00:00Z",
    "updated_at": "2026-02-15T08:00:00Z",
    "printed": true,
    "form_type": "new",
    "ppt_type": "new",
    "executor_type": "internal",
    "executor_name": "ليث جاسم العبيدي",
    "hours": 30,
    "applied": true,
    "location": "قاعة التدريب الرئيسية",
    "trainer_name": "ليث جاسم العبيدي",
    "audience_count": 50,
    "audit_status": "done",
    "file_url": "",
    "file_type": "pdf",
    "hard_copy_printed": true,
    "current_stage": "done",
    "assigned_to": "emp-11",
    "handed_over_by": null,
    "handed_over_at": null
  },
  {
    "id": "cur-8",
    "title": "منهج أخلاقيات العمل الوظيفي",
    "goals": "الهدف من منهج أخلاقيات العمل الوظيفي هو رفع كفاءة المتدربين",
    "target_audience": "جميع الموظفين",
    "count": 60,
    "training_style": "محاضرة",
    "type": "developmental",
    "status": "applied",
    "report_uploaded": true,
    "presentation_uploaded": true,
    "created_by": "emp-4",
    "created_at": "2026-01-10T08:00:00Z",
    "updated_at": "2026-02-15T08:00:00Z",
    "printed": true,
    "form_type": "new",
    "ppt_type": "new",
    "executor_type": "internal",
    "executor_name": "حسن قاسم الربيعي",
    "hours": 8,
    "applied": true,
    "location": "قاعة التدريب الرئيسية",
    "trainer_name": "حسن قاسم الربيعي",
    "audience_count": 60,
    "audit_status": "done",
    "file_url": "",
    "file_type": "pdf",
    "hard_copy_printed": true,
    "current_stage": "done",
    "assigned_to": "emp-10",
    "handed_over_by": null,
    "handed_over_at": null
  }
];
export const SEED_COURSES: Course[] = [
  {
    "id": "crs-1",
    "title": "دورة إدارة المشاريع الاحترافية",
    "code": "PMP-001",
    "type": "internal",
    "training_type": "developmental",
    "venue": "قاعة التدريب الرئيسية",
    "start_date": "2026-04-05",
    "end_date": "2026-04-10",
    "trainer": "أحمد محمد العلي",
    "trainer_id": "emp-1",
    "supervisor": "فاطمة حسن الأمير",
    "supervisor_id": "emp-2",
    "sponsor": "وزارة التعليم",
    "status": "completed",
    "estimated_budget": 50000,
    "actual_cost": 42000,
    "created_by": "emp-1",
    "created_at": "2026-01-05T08:00:00Z",
    "updated_at": "2026-02-10T08:00:00Z"
  },
  {
    "id": "crs-2",
    "title": "دورة الأمن السيبراني المتقدم",
    "code": "CS-002",
    "type": "external",
    "training_type": "specialized",
    "venue": "مركز التدريب التقني",
    "start_date": "2026-05-20",
    "end_date": "2026-05-25",
    "trainer": "محمد علي الزهراني",
    "trainer_id": "emp-5",
    "supervisor": "خالد عبدالله السعيد",
    "supervisor_id": "emp-3",
    "sponsor": "الهيئة الوطنية",
    "status": "planned",
    "estimated_budget": 75000,
    "actual_cost": 0,
    "created_by": "emp-1",
    "created_at": "2026-01-05T08:00:00Z",
    "updated_at": "2026-02-10T08:00:00Z"
  },
  {
    "id": "crs-3",
    "title": "دورة القيادة والإدارة",
    "code": "LD-003",
    "type": "internal",
    "training_type": "developmental",
    "venue": "القاعة الذكية",
    "start_date": "2026-03-10",
    "end_date": "2026-03-15",
    "trainer": "فاطمة حسن الأمير",
    "trainer_id": "emp-2",
    "supervisor": "خالد عبدالله السعيد",
    "supervisor_id": "emp-3",
    "sponsor": "داخلي",
    "status": "completed",
    "estimated_budget": 30000,
    "actual_cost": 28500,
    "created_by": "emp-1",
    "created_at": "2026-01-05T08:00:00Z",
    "updated_at": "2026-02-10T08:00:00Z"
  },
  {
    "id": "crs-4",
    "title": "دورة تحليل البيانات",
    "code": "DA-004",
    "type": "external",
    "training_type": "specialized",
    "venue": "أكاديمية البيانات",
    "start_date": "2026-06-01",
    "end_date": "2026-06-06",
    "trainer": "خبير خارجي",
    "trainer_id": null,
    "supervisor": "نورة سعد المالكي",
    "supervisor_id": "emp-4",
    "sponsor": "صندوق التنمية",
    "status": "planned",
    "estimated_budget": 90000,
    "actual_cost": 0,
    "created_by": "emp-1",
    "created_at": "2026-01-05T08:00:00Z",
    "updated_at": "2026-02-10T08:00:00Z"
  },
  {
    "id": "crs-5",
    "title": "دورة خدمة العملاء المتميزة",
    "code": "CSV-005",
    "type": "internal",
    "training_type": "developmental",
    "venue": "قاعة التدريب ب",
    "start_date": "2026-05-15",
    "end_date": "2026-05-18",
    "trainer": "نورة سعد المالكي",
    "trainer_id": "emp-4",
    "supervisor": "أحمد محمد العلي",
    "supervisor_id": "emp-1",
    "sponsor": "داخلي",
    "status": "active",
    "estimated_budget": 15000,
    "actual_cost": 9000,
    "created_by": "emp-1",
    "created_at": "2026-01-05T08:00:00Z",
    "updated_at": "2026-02-10T08:00:00Z"
  },
  {
    "id": "crs-6",
    "title": "دورة إعداد التقارير الإدارية",
    "code": "RPT-006",
    "type": "internal",
    "training_type": "developmental",
    "venue": "قاعة التدريب أ",
    "start_date": "2026-02-15",
    "end_date": "2026-02-19",
    "trainer": "حسن قاسم الربيعي",
    "trainer_id": "emp-13",
    "supervisor": "فاطمة حسن الأمير",
    "supervisor_id": "emp-2",
    "sponsor": "داخلي",
    "status": "completed",
    "estimated_budget": 18000,
    "actual_cost": 17500,
    "created_by": "emp-1",
    "created_at": "2026-01-05T08:00:00Z",
    "updated_at": "2026-02-10T08:00:00Z"
  },
  {
    "id": "crs-7",
    "title": "دورة Office الاحترافية",
    "code": "OFC-007",
    "type": "internal",
    "training_type": "specialized",
    "venue": "مختبر الحاسوب",
    "start_date": "2026-05-10",
    "end_date": "2026-05-22",
    "trainer": "ليث جاسم العبيدي",
    "trainer_id": "emp-11",
    "supervisor": "نورة سعد المالكي",
    "supervisor_id": "emp-4",
    "sponsor": "داخلي",
    "status": "active",
    "estimated_budget": 22000,
    "actual_cost": 14000,
    "created_by": "emp-1",
    "created_at": "2026-01-05T08:00:00Z",
    "updated_at": "2026-02-10T08:00:00Z"
  },
  {
    "id": "crs-8",
    "title": "دورة أخلاقيات العمل",
    "code": "ETH-008",
    "type": "internal",
    "training_type": "developmental",
    "venue": "القاعة الرئيسية",
    "start_date": "2026-01-15",
    "end_date": "2026-01-18",
    "trainer": "حسن قاسم الربيعي",
    "trainer_id": "emp-13",
    "supervisor": "خالد عبدالله السعيد",
    "supervisor_id": "emp-3",
    "sponsor": "داخلي",
    "status": "completed",
    "estimated_budget": 10000,
    "actual_cost": 9500,
    "created_by": "emp-1",
    "created_at": "2026-01-05T08:00:00Z",
    "updated_at": "2026-02-10T08:00:00Z"
  }
];
export const SEED_TRAINEES: CourseTrainee[] = [
  {
    "id": "tr-1",
    "course_id": "crs-1",
    "employee_id": "emp-5",
    "name": "محمد علي الزهراني",
    "status": "passed",
    "certificate_issued": true,
    "created_at": "2026-04-05T08:00:00Z"
  },
  {
    "id": "tr-2",
    "course_id": "crs-1",
    "employee_id": "emp-12",
    "name": "مريم عادل الحسيني",
    "status": "passed",
    "certificate_issued": true,
    "created_at": "2026-04-05T08:00:00Z"
  },
  {
    "id": "tr-3",
    "course_id": "crs-1",
    "employee_id": "emp-11",
    "name": "ليث جاسم العبيدي",
    "status": "passed",
    "certificate_issued": true,
    "created_at": "2026-04-05T08:00:00Z"
  },
  {
    "id": "tr-4",
    "course_id": "crs-1",
    "employee_id": "emp-6",
    "name": "سارة يوسف القحطاني",
    "status": "passed",
    "certificate_issued": true,
    "created_at": "2026-04-05T08:00:00Z"
  },
  {
    "id": "tr-5",
    "course_id": "crs-2",
    "employee_id": "emp-14",
    "name": "أمل ناصر الجبوري",
    "status": "waiting",
    "certificate_issued": false,
    "created_at": "2026-05-20T08:00:00Z"
  },
  {
    "id": "tr-6",
    "course_id": "crs-2",
    "employee_id": "emp-6",
    "name": "سارة يوسف القحطاني",
    "status": "waiting",
    "certificate_issued": false,
    "created_at": "2026-05-20T08:00:00Z"
  },
  {
    "id": "tr-7",
    "course_id": "crs-3",
    "employee_id": "emp-14",
    "name": "أمل ناصر الجبوري",
    "status": "passed",
    "certificate_issued": true,
    "created_at": "2026-03-10T08:00:00Z"
  },
  {
    "id": "tr-8",
    "course_id": "crs-3",
    "employee_id": "emp-8",
    "name": "هند ماجد العتيبي",
    "status": "failed",
    "certificate_issued": false,
    "created_at": "2026-03-10T08:00:00Z"
  },
  {
    "id": "tr-9",
    "course_id": "crs-3",
    "employee_id": "emp-12",
    "name": "مريم عادل الحسيني",
    "status": "passed",
    "certificate_issued": true,
    "created_at": "2026-03-10T08:00:00Z"
  },
  {
    "id": "tr-10",
    "course_id": "crs-3",
    "employee_id": "emp-11",
    "name": "ليث جاسم العبيدي",
    "status": "passed",
    "certificate_issued": true,
    "created_at": "2026-03-10T08:00:00Z"
  },
  {
    "id": "tr-11",
    "course_id": "crs-4",
    "employee_id": "emp-5",
    "name": "محمد علي الزهراني",
    "status": "waiting",
    "certificate_issued": false,
    "created_at": "2026-06-01T08:00:00Z"
  },
  {
    "id": "tr-12",
    "course_id": "crs-4",
    "employee_id": "emp-6",
    "name": "سارة يوسف القحطاني",
    "status": "waiting",
    "certificate_issued": false,
    "created_at": "2026-06-01T08:00:00Z"
  },
  {
    "id": "tr-13",
    "course_id": "crs-5",
    "employee_id": "emp-9",
    "name": "علي حسين الخفاجي",
    "status": "waiting",
    "certificate_issued": false,
    "created_at": "2026-05-15T08:00:00Z"
  },
  {
    "id": "tr-14",
    "course_id": "crs-5",
    "employee_id": "emp-14",
    "name": "أمل ناصر الجبوري",
    "status": "waiting",
    "certificate_issued": false,
    "created_at": "2026-05-15T08:00:00Z"
  },
  {
    "id": "tr-15",
    "course_id": "crs-5",
    "employee_id": "emp-11",
    "name": "ليث جاسم العبيدي",
    "status": "waiting",
    "certificate_issued": false,
    "created_at": "2026-05-15T08:00:00Z"
  },
  {
    "id": "tr-16",
    "course_id": "crs-6",
    "employee_id": "emp-12",
    "name": "مريم عادل الحسيني",
    "status": "passed",
    "certificate_issued": true,
    "created_at": "2026-02-15T08:00:00Z"
  },
  {
    "id": "tr-17",
    "course_id": "crs-6",
    "employee_id": "emp-11",
    "name": "ليث جاسم العبيدي",
    "status": "passed",
    "certificate_issued": true,
    "created_at": "2026-02-15T08:00:00Z"
  },
  {
    "id": "tr-18",
    "course_id": "crs-6",
    "employee_id": "emp-5",
    "name": "محمد علي الزهراني",
    "status": "passed",
    "certificate_issued": true,
    "created_at": "2026-02-15T08:00:00Z"
  },
  {
    "id": "tr-19",
    "course_id": "crs-6",
    "employee_id": "emp-6",
    "name": "سارة يوسف القحطاني",
    "status": "passed",
    "certificate_issued": true,
    "created_at": "2026-02-15T08:00:00Z"
  },
  {
    "id": "tr-20",
    "course_id": "crs-7",
    "employee_id": "emp-8",
    "name": "هند ماجد العتيبي",
    "status": "waiting",
    "certificate_issued": false,
    "created_at": "2026-05-10T08:00:00Z"
  },
  {
    "id": "tr-21",
    "course_id": "crs-7",
    "employee_id": "emp-12",
    "name": "مريم عادل الحسيني",
    "status": "waiting",
    "certificate_issued": false,
    "created_at": "2026-05-10T08:00:00Z"
  },
  {
    "id": "tr-22",
    "course_id": "crs-7",
    "employee_id": "emp-9",
    "name": "علي حسين الخفاجي",
    "status": "waiting",
    "certificate_issued": false,
    "created_at": "2026-05-10T08:00:00Z"
  },
  {
    "id": "tr-23",
    "course_id": "crs-8",
    "employee_id": "emp-9",
    "name": "علي حسين الخفاجي",
    "status": "passed",
    "certificate_issued": true,
    "created_at": "2026-01-15T08:00:00Z"
  },
  {
    "id": "tr-24",
    "course_id": "crs-8",
    "employee_id": "emp-5",
    "name": "محمد علي الزهراني",
    "status": "passed",
    "certificate_issued": true,
    "created_at": "2026-01-15T08:00:00Z"
  },
  {
    "id": "tr-25",
    "course_id": "crs-8",
    "employee_id": "emp-6",
    "name": "سارة يوسف القحطاني",
    "status": "failed",
    "certificate_issued": false,
    "created_at": "2026-01-15T08:00:00Z"
  },
  {
    "id": "tr-26",
    "course_id": "crs-8",
    "employee_id": "emp-7",
    "name": "عبدالرحمن فهد الشمري",
    "status": "passed",
    "certificate_issued": true,
    "created_at": "2026-01-15T08:00:00Z"
  }
];
export const SEED_HR: HRRequest[] = [
  {
    "id": "hr-1",
    "employee_name": "سارة يوسف القحطاني",
    "department": "شعبة الإعداد والتدريب",
    "type": "إجازة مرضية",
    "date": "2026-05-11",
    "approval_status": "approved",
    "notes": "إجازة مرضية لمدة يومين",
    "created_by": "emp-6",
    "created_at": "2026-05-10T08:00:00Z",
    "updated_at": "2026-05-11T08:00:00Z",
    "unit_head_status": "approved",
    "unit_head_by": "emp-3",
    "unit_head_at": "2026-05-11T08:00:00Z",
    "dept_manager_status": "approved",
    "dept_manager_by": "emp-2",
    "dept_manager_at": "2026-05-11T08:00:00Z"
  },
  {
    "id": "hr-2",
    "employee_name": "عبدالرحمن فهد الشمري",
    "department": "شعبة الإعداد والتدريب",
    "type": "مأمورية",
    "date": "2026-05-12",
    "approval_status": "approved",
    "notes": "مأمورية لمدة يومين",
    "created_by": "emp-7",
    "created_at": "2026-05-11T08:00:00Z",
    "updated_at": "2026-05-12T08:00:00Z",
    "unit_head_status": "approved",
    "unit_head_by": "emp-3",
    "unit_head_at": "2026-05-12T08:00:00Z",
    "dept_manager_status": "approved",
    "dept_manager_by": "emp-2",
    "dept_manager_at": "2026-05-12T08:00:00Z"
  },
  {
    "id": "hr-3",
    "employee_name": "هند ماجد العتيبي",
    "department": "شعبة الإعداد والتدريب",
    "type": "خروجية",
    "date": "2026-05-13",
    "approval_status": "approved",
    "notes": "خروجية لمدة يومين",
    "created_by": "emp-8",
    "created_at": "2026-05-12T08:00:00Z",
    "updated_at": "2026-05-13T08:00:00Z",
    "unit_head_status": "approved",
    "unit_head_by": "emp-3",
    "unit_head_at": "2026-05-13T08:00:00Z",
    "dept_manager_status": "approved",
    "dept_manager_by": "emp-2",
    "dept_manager_at": "2026-05-13T08:00:00Z"
  },
  {
    "id": "hr-4",
    "employee_name": "علي حسين الخفاجي",
    "department": "شعبة الإعداد والتدريب",
    "type": "إجازة زواج",
    "date": "2026-05-14",
    "approval_status": "unit_approved",
    "notes": "إجازة زواج لمدة يومين",
    "created_by": "emp-9",
    "created_at": "2026-05-13T08:00:00Z",
    "updated_at": "2026-05-14T08:00:00Z",
    "unit_head_status": "approved",
    "unit_head_by": "emp-3",
    "unit_head_at": "2026-05-14T08:00:00Z",
    "dept_manager_status": "pending",
    "dept_manager_by": null,
    "dept_manager_at": null
  },
  {
    "id": "hr-5",
    "employee_name": "زينب كريم الموسوي",
    "department": "شعبة المناهج",
    "type": "استئذان",
    "date": "2026-05-15",
    "approval_status": "unit_approved",
    "notes": "استئذان لمدة يومين",
    "created_by": "emp-10",
    "created_at": "2026-05-14T08:00:00Z",
    "updated_at": "2026-05-15T08:00:00Z",
    "unit_head_status": "approved",
    "unit_head_by": "emp-4",
    "unit_head_at": "2026-05-15T08:00:00Z",
    "dept_manager_status": "pending",
    "dept_manager_by": null,
    "dept_manager_at": null
  },
  {
    "id": "hr-6",
    "employee_name": "ليث جاسم العبيدي",
    "department": "شعبة المناهج",
    "type": "إجازة اعتيادية",
    "date": "2026-05-16",
    "approval_status": "rejected",
    "notes": "إجازة اعتيادية لمدة يومين",
    "created_by": "emp-11",
    "created_at": "2026-05-15T08:00:00Z",
    "updated_at": "2026-05-16T08:00:00Z",
    "unit_head_status": "rejected",
    "unit_head_by": "emp-4",
    "unit_head_at": "2026-05-16T08:00:00Z",
    "dept_manager_status": "pending",
    "dept_manager_by": null,
    "dept_manager_at": null
  },
  {
    "id": "hr-7",
    "employee_name": "مريم عادل الحسيني",
    "department": "شعبة المناهج",
    "type": "إجازة مرضية",
    "date": "2026-05-17",
    "approval_status": "pending",
    "notes": "إجازة مرضية لمدة يومين",
    "created_by": "emp-12",
    "created_at": "2026-05-16T08:00:00Z",
    "updated_at": "2026-05-17T08:00:00Z",
    "unit_head_status": "pending",
    "unit_head_by": null,
    "unit_head_at": null,
    "dept_manager_status": "pending",
    "dept_manager_by": null,
    "dept_manager_at": null
  },
  {
    "id": "hr-8",
    "employee_name": "حسن قاسم الربيعي",
    "department": "شعبة المناهج",
    "type": "مأمورية",
    "date": "2026-05-18",
    "approval_status": "pending",
    "notes": "مأمورية لمدة يومين",
    "created_by": "emp-13",
    "created_at": "2026-05-17T08:00:00Z",
    "updated_at": "2026-05-18T08:00:00Z",
    "unit_head_status": "pending",
    "unit_head_by": null,
    "unit_head_at": null,
    "dept_manager_status": "pending",
    "dept_manager_by": null,
    "dept_manager_at": null
  },
  {
    "id": "hr-9",
    "employee_name": "أمل ناصر الجبوري",
    "department": "شعبة المناهج",
    "type": "خروجية",
    "date": "2026-05-19",
    "approval_status": "pending",
    "notes": "خروجية لمدة يومين",
    "created_by": "emp-14",
    "created_at": "2026-05-18T08:00:00Z",
    "updated_at": "2026-05-19T08:00:00Z",
    "unit_head_status": "pending",
    "unit_head_by": null,
    "unit_head_at": null,
    "dept_manager_status": "pending",
    "dept_manager_by": null,
    "dept_manager_at": null
  },
  {
    "id": "hr-10",
    "employee_name": "محمد علي الزهراني",
    "department": "شعبة الإعداد والتدريب",
    "type": "إجازة زواج",
    "date": "2026-05-20",
    "approval_status": "pending",
    "notes": "إجازة زواج لمدة يومين",
    "created_by": "emp-5",
    "created_at": "2026-05-19T08:00:00Z",
    "updated_at": "2026-05-20T08:00:00Z",
    "unit_head_status": "pending",
    "unit_head_by": null,
    "unit_head_at": null,
    "dept_manager_status": "pending",
    "dept_manager_by": null,
    "dept_manager_at": null
  }
];
export const SEED_CORRESPONDENCE: CorrespondenceItem[] = [
  {
    "id": "cor-1",
    "number": "ص/2026/001",
    "date": "2026-02-10",
    "subject": "طلب تنسيق برنامج تدريبي",
    "from": "إدارة التدريب",
    "to": "وزارة التعليم",
    "type": "outgoing_external",
    "status": "done",
    "summary": "تنسيق برنامج مشترك",
    "created_by": "emp-2",
    "created_at": "2026-02-10T08:00:00Z",
    "updated_at": "2026-02-10T08:00:00Z"
  },
  {
    "id": "cor-2",
    "number": "و/2026/015",
    "date": "2026-02-08",
    "subject": "الموافقة على الميزانية التدريبية",
    "from": "الإدارة المالية",
    "to": "إدارة التدريب",
    "type": "incoming_internal",
    "status": "done",
    "summary": "اعتماد الميزانية",
    "created_by": "emp-7",
    "created_at": "2026-02-08T08:00:00Z",
    "updated_at": "2026-02-08T08:00:00Z"
  },
  {
    "id": "cor-3",
    "number": "ص/2026/002",
    "date": "2026-03-12",
    "subject": "دعوة لحضور ملتقى تدريبي",
    "from": "إدارة التدريب",
    "to": "فروع المحافظات",
    "type": "outgoing_internal",
    "status": "archived",
    "summary": "الملتقى السنوي",
    "created_by": "emp-2",
    "created_at": "2026-03-12T08:00:00Z",
    "updated_at": "2026-03-12T08:00:00Z"
  },
  {
    "id": "cor-4",
    "number": "و/2026/020",
    "date": "2026-01-15",
    "subject": "تقرير إنجاز سنوي 2025",
    "from": "الجهة الرقابية",
    "to": "إدارة التدريب",
    "type": "incoming_external",
    "status": "archived",
    "summary": "تقرير الإنجاز",
    "created_by": "emp-7",
    "created_at": "2026-01-15T08:00:00Z",
    "updated_at": "2026-01-15T08:00:00Z"
  },
  {
    "id": "cor-5",
    "number": "ص/2026/003",
    "date": "2026-04-14",
    "subject": "متابعة شهادات التدريب",
    "from": "شعبة الإعداد",
    "to": "شعبة المناهج",
    "type": "outgoing_internal",
    "status": "in_progress",
    "summary": "إصدار الشهادات",
    "created_by": "emp-3",
    "created_at": "2026-04-14T08:00:00Z",
    "updated_at": "2026-04-14T08:00:00Z"
  },
  {
    "id": "cor-6",
    "number": "و/2026/030",
    "date": "2026-04-20",
    "subject": "كتاب شكر للمتدربين",
    "from": "الإدارة العامة",
    "to": "إدارة التدريب",
    "type": "incoming_internal",
    "status": "archived",
    "summary": "شكر وتقدير",
    "created_by": "emp-7",
    "created_at": "2026-04-20T08:00:00Z",
    "updated_at": "2026-04-20T08:00:00Z"
  },
  {
    "id": "cor-7",
    "number": "ص/2026/004",
    "date": "2026-05-01",
    "subject": "طلب نقل موظف",
    "from": "الموارد البشرية",
    "to": "الإدارة العامة",
    "type": "outgoing_internal",
    "status": "in_progress",
    "summary": "طلب نقل",
    "created_by": "emp-5",
    "created_at": "2026-05-01T08:00:00Z",
    "updated_at": "2026-05-01T08:00:00Z"
  },
  {
    "id": "cor-8",
    "number": "و/2026/035",
    "date": "2026-05-12",
    "subject": "تعميم إجازة العيد",
    "from": "الإدارة العامة",
    "to": "كافة الشعب",
    "type": "incoming_internal",
    "status": "done",
    "summary": "تعميم رسمي",
    "created_by": "emp-7",
    "created_at": "2026-05-12T08:00:00Z",
    "updated_at": "2026-05-12T08:00:00Z"
  }
];
export const SEED_TASKS: Task[] = [
  {
    "id": "tsk-1",
    "title": "إعداد منهج الأمن السيبراني",
    "description": "كتابة المحتوى التعليمي",
    "unit": "المناهج",
    "stage": "auditing",
    "status": "in_progress",
    "assigned_to": "emp-10",
    "assigned_by": "emp-4",
    "previous_owner": null,
    "handed_over": false,
    "handed_over_at": null,
    "curriculum_item_id": "cur-2",
    "achievement_points": 2,
    "estimated_hours": 40,
    "is_routine": false,
    "created_by": "emp-4",
    "created_at": "2026-04-20T08:00:00Z",
    "updated_at": "2026-05-15T08:00:00Z"
  },
  {
    "id": "tsk-2",
    "title": "تنسيق دورة PMP",
    "description": "ترتيب القاعة والمدرب",
    "unit": "الإعداد",
    "stage": "routine",
    "status": "completed",
    "assigned_to": "emp-6",
    "assigned_by": "emp-3",
    "previous_owner": null,
    "handed_over": true,
    "handed_over_at": "2026-05-15T08:00:00Z",
    "curriculum_item_id": null,
    "achievement_points": 1,
    "estimated_hours": 8,
    "is_routine": true,
    "created_by": "emp-3",
    "created_at": "2026-04-20T08:00:00Z",
    "updated_at": "2026-05-15T08:00:00Z"
  },
  {
    "id": "tsk-3",
    "title": "تحديث منهج القيادة",
    "description": "تحديث المحتوى القديم",
    "unit": "المناهج",
    "stage": "writing",
    "status": "pending",
    "assigned_to": "emp-10",
    "assigned_by": "emp-4",
    "previous_owner": null,
    "handed_over": false,
    "handed_over_at": null,
    "curriculum_item_id": "cur-3",
    "achievement_points": 0,
    "estimated_hours": 20,
    "is_routine": false,
    "created_by": "emp-4",
    "created_at": "2026-04-20T08:00:00Z",
    "updated_at": "2026-05-15T08:00:00Z"
  },
  {
    "id": "tsk-4",
    "title": "متابعة إصدار الشهادات",
    "description": "إصدار شهادات الدورة المنتهية",
    "unit": "الإعداد",
    "stage": "routine",
    "status": "in_progress",
    "assigned_to": "emp-8",
    "assigned_by": "emp-3",
    "previous_owner": null,
    "handed_over": false,
    "handed_over_at": null,
    "curriculum_item_id": null,
    "achievement_points": 0,
    "estimated_hours": 4,
    "is_routine": true,
    "created_by": "emp-3",
    "created_at": "2026-04-20T08:00:00Z",
    "updated_at": "2026-05-15T08:00:00Z"
  },
  {
    "id": "tsk-5",
    "title": "إعداد عرض القيادة",
    "description": "تصميم العرض التقديمي",
    "unit": "المناهج",
    "stage": "new_ppt",
    "status": "review",
    "assigned_to": "emp-11",
    "assigned_by": "emp-4",
    "previous_owner": null,
    "handed_over": false,
    "handed_over_at": null,
    "curriculum_item_id": "cur-3",
    "achievement_points": 1,
    "estimated_hours": 6,
    "is_routine": false,
    "created_by": "emp-4",
    "created_at": "2026-04-20T08:00:00Z",
    "updated_at": "2026-05-15T08:00:00Z"
  },
  {
    "id": "tsk-6",
    "title": "أرشفة كتب الإصدارات السابقة",
    "description": "أرشفة الكتب الرسمية",
    "unit": "الأرشيف",
    "stage": "routine",
    "status": "completed",
    "assigned_to": "emp-7",
    "assigned_by": "emp-3",
    "previous_owner": null,
    "handed_over": true,
    "handed_over_at": "2026-05-15T08:00:00Z",
    "curriculum_item_id": null,
    "achievement_points": 1,
    "estimated_hours": 5,
    "is_routine": true,
    "created_by": "emp-3",
    "created_at": "2026-04-20T08:00:00Z",
    "updated_at": "2026-05-15T08:00:00Z"
  },
  {
    "id": "tsk-7",
    "title": "إعداد تقرير الأداء الشهري",
    "description": "تجميع تقرير شهر أيار",
    "unit": "التقارير",
    "stage": "writing",
    "status": "in_progress",
    "assigned_to": "emp-9",
    "assigned_by": "emp-3",
    "previous_owner": null,
    "handed_over": false,
    "handed_over_at": null,
    "curriculum_item_id": null,
    "achievement_points": 0,
    "estimated_hours": 10,
    "is_routine": false,
    "created_by": "emp-3",
    "created_at": "2026-04-20T08:00:00Z",
    "updated_at": "2026-05-15T08:00:00Z"
  },
  {
    "id": "tsk-8",
    "title": "تنفيذ دورة Office",
    "description": "متابعة سير الدورة",
    "unit": "التنفيذ التدريبي",
    "stage": "routine",
    "status": "in_progress",
    "assigned_to": "emp-8",
    "assigned_by": "emp-3",
    "previous_owner": null,
    "handed_over": false,
    "handed_over_at": null,
    "curriculum_item_id": "cur-7",
    "achievement_points": 0,
    "estimated_hours": 30,
    "is_routine": false,
    "created_by": "emp-3",
    "created_at": "2026-04-20T08:00:00Z",
    "updated_at": "2026-05-15T08:00:00Z"
  },
  {
    "id": "tsk-9",
    "title": "إعداد خطة التدريب لشهر حزيران",
    "description": "جدولة الدورات القادمة",
    "unit": "الخطة التدريبية",
    "stage": "writing",
    "status": "pending",
    "assigned_to": "emp-12",
    "assigned_by": "emp-4",
    "previous_owner": null,
    "handed_over": false,
    "handed_over_at": null,
    "curriculum_item_id": null,
    "achievement_points": 0,
    "estimated_hours": 12,
    "is_routine": false,
    "created_by": "emp-4",
    "created_at": "2026-04-20T08:00:00Z",
    "updated_at": "2026-05-15T08:00:00Z"
  },
  {
    "id": "tsk-10",
    "title": "تقييم دورة القيادة المنتهية",
    "description": "جمع وتحليل تقييمات المتدربين",
    "unit": "التقييم",
    "stage": "routine",
    "status": "in_progress",
    "assigned_to": "emp-13",
    "assigned_by": "emp-4",
    "previous_owner": null,
    "handed_over": false,
    "handed_over_at": null,
    "curriculum_item_id": null,
    "achievement_points": 0,
    "estimated_hours": 6,
    "is_routine": false,
    "created_by": "emp-4",
    "created_at": "2026-04-20T08:00:00Z",
    "updated_at": "2026-05-15T08:00:00Z"
  }
];
export const SEED_GOV_TRAINING: GovernorateTraining[] = [
  {
    "id": "gt-1",
    "governorate": "بغداد",
    "course_name": "منهج إدارة المشاريع الاحترافية",
    "domain": "إدارية",
    "course_hours": 8,
    "track": "المسار الأول",
    "nominees_count": 5,
    "planned_start_date": "2026-03-05",
    "planned_end_date": "2026-03-10",
    "actual_start_date": "2026-03-11",
    "actual_end_date": "2026-03-16",
    "status": "completed",
    "compliance": "completed",
    "notes": "",
    "created_by": "emp-3",
    "created_at": "2026-03-01T08:00:00Z",
    "updated_at": "2026-04-15T08:00:00Z"
  },
  {
    "id": "gt-2",
    "governorate": "بغداد",
    "course_name": "منهج تحليل البيانات وذكاء الأعمال",
    "domain": "تقنية المعلومات",
    "course_hours": 8,
    "track": "المسار الثاني",
    "nominees_count": 5,
    "planned_start_date": "2026-04-05",
    "planned_end_date": "2026-04-10",
    "actual_start_date": "2026-04-5",
    "actual_end_date": null,
    "status": "in_progress",
    "compliance": "delayed",
    "notes": "تأخر يوم بسبب ظروف الطقس",
    "created_by": "emp-4",
    "created_at": "2026-03-01T08:00:00Z",
    "updated_at": "2026-04-15T08:00:00Z"
  },
  {
    "id": "gt-3",
    "governorate": "البصرة",
    "course_name": "منهج الأمن السيبراني المتقدم",
    "domain": "تقنية المعلومات",
    "course_hours": 12,
    "track": "المسار الثاني",
    "nominees_count": 5,
    "planned_start_date": "2026-03-06",
    "planned_end_date": "2026-03-11",
    "actual_start_date": "2026-03-12",
    "actual_end_date": "2026-03-17",
    "status": "completed",
    "compliance": "completed",
    "notes": "",
    "created_by": "emp-3",
    "created_at": "2026-03-01T08:00:00Z",
    "updated_at": "2026-04-15T08:00:00Z"
  },
  {
    "id": "gt-4",
    "governorate": "البصرة",
    "course_name": "منهج مهارات التواصل المؤسسي",
    "domain": "قيادية",
    "course_hours": 12,
    "track": "المسار الثالث",
    "nominees_count": 5,
    "planned_start_date": "2026-04-06",
    "planned_end_date": "2026-04-11",
    "actual_start_date": null,
    "actual_end_date": null,
    "status": "planned",
    "compliance": "on_track",
    "notes": "",
    "created_by": "emp-4",
    "created_at": "2026-03-01T08:00:00Z",
    "updated_at": "2026-04-15T08:00:00Z"
  },
  {
    "id": "gt-5",
    "governorate": "نينوى",
    "course_name": "منهج تحليل البيانات وذكاء الأعمال",
    "domain": "قيادية",
    "course_hours": 16,
    "track": "المسار الثالث",
    "nominees_count": 5,
    "planned_start_date": "2026-03-07",
    "planned_end_date": "2026-03-12",
    "actual_start_date": "2026-03-13",
    "actual_end_date": "2026-03-18",
    "status": "completed",
    "compliance": "completed",
    "notes": "",
    "created_by": "emp-3",
    "created_at": "2026-03-01T08:00:00Z",
    "updated_at": "2026-04-15T08:00:00Z"
  },
  {
    "id": "gt-6",
    "governorate": "نينوى",
    "course_name": "منهج الإدارة الإلكترونية / Office",
    "domain": "إدارية",
    "course_hours": 16,
    "track": "المسار الأول",
    "nominees_count": 5,
    "planned_start_date": "2026-04-07",
    "planned_end_date": "2026-04-12",
    "actual_start_date": "2026-04-7",
    "actual_end_date": "2026-04-12",
    "status": "completed",
    "compliance": "on_track",
    "notes": "",
    "created_by": "emp-4",
    "created_at": "2026-03-01T08:00:00Z",
    "updated_at": "2026-04-15T08:00:00Z"
  },
  {
    "id": "gt-7",
    "governorate": "ذي قار",
    "course_name": "منهج مهارات التواصل المؤسسي",
    "domain": "إدارية",
    "course_hours": 8,
    "track": "المسار الأول",
    "nominees_count": 5,
    "planned_start_date": "2026-03-08",
    "planned_end_date": "2026-03-13",
    "actual_start_date": "2026-03-14",
    "actual_end_date": "2026-03-19",
    "status": "completed",
    "compliance": "completed",
    "notes": "",
    "created_by": "emp-3",
    "created_at": "2026-03-01T08:00:00Z",
    "updated_at": "2026-04-15T08:00:00Z"
  },
  {
    "id": "gt-8",
    "governorate": "ذي قار",
    "course_name": "منهج أخلاقيات العمل الوظيفي",
    "domain": "تقنية المعلومات",
    "course_hours": 8,
    "track": "المسار الثاني",
    "nominees_count": 5,
    "planned_start_date": "2026-04-08",
    "planned_end_date": "2026-04-13",
    "actual_start_date": "2026-04-8",
    "actual_end_date": null,
    "status": "in_progress",
    "compliance": "on_track",
    "notes": "",
    "created_by": "emp-4",
    "created_at": "2026-03-01T08:00:00Z",
    "updated_at": "2026-04-15T08:00:00Z"
  },
  {
    "id": "gt-9",
    "governorate": "السليمانية",
    "course_name": "منهج الإدارة الإلكترونية / Office",
    "domain": "تقنية المعلومات",
    "course_hours": 12,
    "track": "المسار الثاني",
    "nominees_count": 5,
    "planned_start_date": "2026-03-09",
    "planned_end_date": "2026-03-14",
    "actual_start_date": "2026-03-15",
    "actual_end_date": "2026-03-20",
    "status": "completed",
    "compliance": "completed",
    "notes": "",
    "created_by": "emp-3",
    "created_at": "2026-03-01T08:00:00Z",
    "updated_at": "2026-04-15T08:00:00Z"
  },
  {
    "id": "gt-10",
    "governorate": "السليمانية",
    "course_name": "منهج إدارة المشاريع الاحترافية",
    "domain": "قيادية",
    "course_hours": 12,
    "track": "المسار الثالث",
    "nominees_count": 5,
    "planned_start_date": "2026-04-09",
    "planned_end_date": "2026-04-14",
    "actual_start_date": null,
    "actual_end_date": null,
    "status": "planned",
    "compliance": "delayed",
    "notes": "تأخر يوم بسبب ظروف الطقس",
    "created_by": "emp-4",
    "created_at": "2026-03-01T08:00:00Z",
    "updated_at": "2026-04-15T08:00:00Z"
  },
  {
    "id": "gt-11",
    "governorate": "بابل",
    "course_name": "منهج أخلاقيات العمل الوظيفي",
    "domain": "قيادية",
    "course_hours": 16,
    "track": "المسار الثالث",
    "nominees_count": 5,
    "planned_start_date": "2026-03-10",
    "planned_end_date": "2026-03-15",
    "actual_start_date": "2026-03-16",
    "actual_end_date": "2026-03-21",
    "status": "completed",
    "compliance": "completed",
    "notes": "",
    "created_by": "emp-3",
    "created_at": "2026-03-01T08:00:00Z",
    "updated_at": "2026-04-15T08:00:00Z"
  },
  {
    "id": "gt-12",
    "governorate": "بابل",
    "course_name": "منهج الأمن السيبراني المتقدم",
    "domain": "إدارية",
    "course_hours": 16,
    "track": "المسار الأول",
    "nominees_count": 5,
    "planned_start_date": "2026-04-10",
    "planned_end_date": "2026-04-15",
    "actual_start_date": "2026-04-10",
    "actual_end_date": "2026-04-15",
    "status": "completed",
    "compliance": "on_track",
    "notes": "",
    "created_by": "emp-4",
    "created_at": "2026-03-01T08:00:00Z",
    "updated_at": "2026-04-15T08:00:00Z"
  },
  {
    "id": "gt-13",
    "governorate": "ديالى",
    "course_name": "منهج إدارة المشاريع الاحترافية",
    "domain": "إدارية",
    "course_hours": 8,
    "track": "المسار الأول",
    "nominees_count": 5,
    "planned_start_date": "2026-03-11",
    "planned_end_date": "2026-03-16",
    "actual_start_date": "2026-03-17",
    "actual_end_date": "2026-03-22",
    "status": "completed",
    "compliance": "completed",
    "notes": "",
    "created_by": "emp-3",
    "created_at": "2026-03-01T08:00:00Z",
    "updated_at": "2026-04-15T08:00:00Z"
  },
  {
    "id": "gt-14",
    "governorate": "ديالى",
    "course_name": "منهج تحليل البيانات وذكاء الأعمال",
    "domain": "تقنية المعلومات",
    "course_hours": 8,
    "track": "المسار الثاني",
    "nominees_count": 5,
    "planned_start_date": "2026-04-11",
    "planned_end_date": "2026-04-16",
    "actual_start_date": "2026-04-11",
    "actual_end_date": null,
    "status": "in_progress",
    "compliance": "on_track",
    "notes": "",
    "created_by": "emp-4",
    "created_at": "2026-03-01T08:00:00Z",
    "updated_at": "2026-04-15T08:00:00Z"
  },
  {
    "id": "gt-15",
    "governorate": "الأنبار",
    "course_name": "منهج الأمن السيبراني المتقدم",
    "domain": "تقنية المعلومات",
    "course_hours": 12,
    "track": "المسار الثاني",
    "nominees_count": 5,
    "planned_start_date": "2026-03-12",
    "planned_end_date": "2026-03-17",
    "actual_start_date": "2026-03-18",
    "actual_end_date": "2026-03-23",
    "status": "completed",
    "compliance": "completed",
    "notes": "",
    "created_by": "emp-3",
    "created_at": "2026-03-01T08:00:00Z",
    "updated_at": "2026-04-15T08:00:00Z"
  },
  {
    "id": "gt-16",
    "governorate": "الأنبار",
    "course_name": "منهج مهارات التواصل المؤسسي",
    "domain": "قيادية",
    "course_hours": 12,
    "track": "المسار الثالث",
    "nominees_count": 5,
    "planned_start_date": "2026-04-12",
    "planned_end_date": "2026-04-17",
    "actual_start_date": null,
    "actual_end_date": null,
    "status": "planned",
    "compliance": "on_track",
    "notes": "",
    "created_by": "emp-4",
    "created_at": "2026-03-01T08:00:00Z",
    "updated_at": "2026-04-15T08:00:00Z"
  },
  {
    "id": "gt-17",
    "governorate": "كركوك",
    "course_name": "منهج تحليل البيانات وذكاء الأعمال",
    "domain": "قيادية",
    "course_hours": 16,
    "track": "المسار الثالث",
    "nominees_count": 5,
    "planned_start_date": "2026-03-13",
    "planned_end_date": "2026-03-18",
    "actual_start_date": "2026-03-19",
    "actual_end_date": "2026-03-24",
    "status": "completed",
    "compliance": "completed",
    "notes": "",
    "created_by": "emp-3",
    "created_at": "2026-03-01T08:00:00Z",
    "updated_at": "2026-04-15T08:00:00Z"
  },
  {
    "id": "gt-18",
    "governorate": "كركوك",
    "course_name": "منهج الإدارة الإلكترونية / Office",
    "domain": "إدارية",
    "course_hours": 16,
    "track": "المسار الأول",
    "nominees_count": 5,
    "planned_start_date": "2026-04-13",
    "planned_end_date": "2026-04-18",
    "actual_start_date": "2026-04-13",
    "actual_end_date": "2026-04-18",
    "status": "completed",
    "compliance": "delayed",
    "notes": "تأخر يوم بسبب ظروف الطقس",
    "created_by": "emp-4",
    "created_at": "2026-03-01T08:00:00Z",
    "updated_at": "2026-04-15T08:00:00Z"
  },
  {
    "id": "gt-19",
    "governorate": "واسط",
    "course_name": "منهج مهارات التواصل المؤسسي",
    "domain": "إدارية",
    "course_hours": 8,
    "track": "المسار الأول",
    "nominees_count": 5,
    "planned_start_date": "2026-03-14",
    "planned_end_date": "2026-03-19",
    "actual_start_date": "2026-03-20",
    "actual_end_date": "2026-03-25",
    "status": "completed",
    "compliance": "completed",
    "notes": "",
    "created_by": "emp-3",
    "created_at": "2026-03-01T08:00:00Z",
    "updated_at": "2026-04-15T08:00:00Z"
  },
  {
    "id": "gt-20",
    "governorate": "واسط",
    "course_name": "منهج أخلاقيات العمل الوظيفي",
    "domain": "تقنية المعلومات",
    "course_hours": 8,
    "track": "المسار الثاني",
    "nominees_count": 5,
    "planned_start_date": "2026-04-14",
    "planned_end_date": "2026-04-19",
    "actual_start_date": "2026-04-14",
    "actual_end_date": null,
    "status": "in_progress",
    "compliance": "on_track",
    "notes": "",
    "created_by": "emp-4",
    "created_at": "2026-03-01T08:00:00Z",
    "updated_at": "2026-04-15T08:00:00Z"
  },
  {
    "id": "gt-21",
    "governorate": "صلاح الدين",
    "course_name": "منهج الإدارة الإلكترونية / Office",
    "domain": "تقنية المعلومات",
    "course_hours": 12,
    "track": "المسار الثاني",
    "nominees_count": 5,
    "planned_start_date": "2026-03-15",
    "planned_end_date": "2026-03-20",
    "actual_start_date": "2026-03-21",
    "actual_end_date": "2026-03-26",
    "status": "completed",
    "compliance": "completed",
    "notes": "",
    "created_by": "emp-3",
    "created_at": "2026-03-01T08:00:00Z",
    "updated_at": "2026-04-15T08:00:00Z"
  },
  {
    "id": "gt-22",
    "governorate": "صلاح الدين",
    "course_name": "منهج إدارة المشاريع الاحترافية",
    "domain": "قيادية",
    "course_hours": 12,
    "track": "المسار الثالث",
    "nominees_count": 5,
    "planned_start_date": "2026-04-15",
    "planned_end_date": "2026-04-20",
    "actual_start_date": null,
    "actual_end_date": null,
    "status": "planned",
    "compliance": "on_track",
    "notes": "",
    "created_by": "emp-4",
    "created_at": "2026-03-01T08:00:00Z",
    "updated_at": "2026-04-15T08:00:00Z"
  },
  {
    "id": "gt-23",
    "governorate": "النجف",
    "course_name": "منهج أخلاقيات العمل الوظيفي",
    "domain": "قيادية",
    "course_hours": 16,
    "track": "المسار الثالث",
    "nominees_count": 5,
    "planned_start_date": "2026-03-16",
    "planned_end_date": "2026-03-21",
    "actual_start_date": "2026-03-22",
    "actual_end_date": "2026-03-27",
    "status": "completed",
    "compliance": "completed",
    "notes": "",
    "created_by": "emp-3",
    "created_at": "2026-03-01T08:00:00Z",
    "updated_at": "2026-04-15T08:00:00Z"
  },
  {
    "id": "gt-24",
    "governorate": "النجف",
    "course_name": "منهج الأمن السيبراني المتقدم",
    "domain": "إدارية",
    "course_hours": 16,
    "track": "المسار الأول",
    "nominees_count": 5,
    "planned_start_date": "2026-04-16",
    "planned_end_date": "2026-04-21",
    "actual_start_date": "2026-04-16",
    "actual_end_date": "2026-04-21",
    "status": "completed",
    "compliance": "on_track",
    "notes": "",
    "created_by": "emp-4",
    "created_at": "2026-03-01T08:00:00Z",
    "updated_at": "2026-04-15T08:00:00Z"
  },
  {
    "id": "gt-25",
    "governorate": "القادسية",
    "course_name": "منهج إدارة المشاريع الاحترافية",
    "domain": "إدارية",
    "course_hours": 8,
    "track": "المسار الأول",
    "nominees_count": 5,
    "planned_start_date": "2026-03-17",
    "planned_end_date": "2026-03-22",
    "actual_start_date": "2026-03-23",
    "actual_end_date": "2026-03-28",
    "status": "completed",
    "compliance": "completed",
    "notes": "",
    "created_by": "emp-3",
    "created_at": "2026-03-01T08:00:00Z",
    "updated_at": "2026-04-15T08:00:00Z"
  },
  {
    "id": "gt-26",
    "governorate": "القادسية",
    "course_name": "منهج تحليل البيانات وذكاء الأعمال",
    "domain": "تقنية المعلومات",
    "course_hours": 8,
    "track": "المسار الثاني",
    "nominees_count": 5,
    "planned_start_date": "2026-04-17",
    "planned_end_date": "2026-04-22",
    "actual_start_date": "2026-04-17",
    "actual_end_date": null,
    "status": "in_progress",
    "compliance": "delayed",
    "notes": "تأخر يوم بسبب ظروف الطقس",
    "created_by": "emp-4",
    "created_at": "2026-03-01T08:00:00Z",
    "updated_at": "2026-04-15T08:00:00Z"
  },
  {
    "id": "gt-27",
    "governorate": "ميسان",
    "course_name": "منهج الأمن السيبراني المتقدم",
    "domain": "تقنية المعلومات",
    "course_hours": 12,
    "track": "المسار الثاني",
    "nominees_count": 5,
    "planned_start_date": "2026-03-18",
    "planned_end_date": "2026-03-23",
    "actual_start_date": "2026-03-24",
    "actual_end_date": "2026-03-29",
    "status": "completed",
    "compliance": "completed",
    "notes": "",
    "created_by": "emp-3",
    "created_at": "2026-03-01T08:00:00Z",
    "updated_at": "2026-04-15T08:00:00Z"
  },
  {
    "id": "gt-28",
    "governorate": "ميسان",
    "course_name": "منهج مهارات التواصل المؤسسي",
    "domain": "قيادية",
    "course_hours": 12,
    "track": "المسار الثالث",
    "nominees_count": 5,
    "planned_start_date": "2026-04-18",
    "planned_end_date": "2026-04-23",
    "actual_start_date": null,
    "actual_end_date": null,
    "status": "planned",
    "compliance": "on_track",
    "notes": "",
    "created_by": "emp-4",
    "created_at": "2026-03-01T08:00:00Z",
    "updated_at": "2026-04-15T08:00:00Z"
  },
  {
    "id": "gt-29",
    "governorate": "أربيل",
    "course_name": "منهج تحليل البيانات وذكاء الأعمال",
    "domain": "قيادية",
    "course_hours": 16,
    "track": "المسار الثالث",
    "nominees_count": 5,
    "planned_start_date": "2026-03-19",
    "planned_end_date": "2026-03-24",
    "actual_start_date": "2026-03-25",
    "actual_end_date": "2026-03-30",
    "status": "completed",
    "compliance": "completed",
    "notes": "",
    "created_by": "emp-3",
    "created_at": "2026-03-01T08:00:00Z",
    "updated_at": "2026-04-15T08:00:00Z"
  },
  {
    "id": "gt-30",
    "governorate": "أربيل",
    "course_name": "منهج الإدارة الإلكترونية / Office",
    "domain": "إدارية",
    "course_hours": 16,
    "track": "المسار الأول",
    "nominees_count": 5,
    "planned_start_date": "2026-04-19",
    "planned_end_date": "2026-04-24",
    "actual_start_date": "2026-04-19",
    "actual_end_date": "2026-04-24",
    "status": "completed",
    "compliance": "on_track",
    "notes": "",
    "created_by": "emp-4",
    "created_at": "2026-03-01T08:00:00Z",
    "updated_at": "2026-04-15T08:00:00Z"
  },
  {
    "id": "gt-31",
    "governorate": "دهوك",
    "course_name": "منهج مهارات التواصل المؤسسي",
    "domain": "إدارية",
    "course_hours": 8,
    "track": "المسار الأول",
    "nominees_count": 5,
    "planned_start_date": "2026-03-20",
    "planned_end_date": "2026-03-25",
    "actual_start_date": "2026-03-11",
    "actual_end_date": "2026-03-16",
    "status": "completed",
    "compliance": "completed",
    "notes": "",
    "created_by": "emp-3",
    "created_at": "2026-03-01T08:00:00Z",
    "updated_at": "2026-04-15T08:00:00Z"
  },
  {
    "id": "gt-32",
    "governorate": "دهوك",
    "course_name": "منهج أخلاقيات العمل الوظيفي",
    "domain": "تقنية المعلومات",
    "course_hours": 8,
    "track": "المسار الثاني",
    "nominees_count": 5,
    "planned_start_date": "2026-04-20",
    "planned_end_date": "2026-04-25",
    "actual_start_date": "2026-04-20",
    "actual_end_date": null,
    "status": "in_progress",
    "compliance": "on_track",
    "notes": "",
    "created_by": "emp-4",
    "created_at": "2026-03-01T08:00:00Z",
    "updated_at": "2026-04-15T08:00:00Z"
  },
  {
    "id": "gt-33",
    "governorate": "كربلاء",
    "course_name": "منهج الإدارة الإلكترونية / Office",
    "domain": "تقنية المعلومات",
    "course_hours": 12,
    "track": "المسار الثاني",
    "nominees_count": 5,
    "planned_start_date": "2026-03-21",
    "planned_end_date": "2026-03-26",
    "actual_start_date": "2026-03-12",
    "actual_end_date": "2026-03-17",
    "status": "completed",
    "compliance": "completed",
    "notes": "",
    "created_by": "emp-3",
    "created_at": "2026-03-01T08:00:00Z",
    "updated_at": "2026-04-15T08:00:00Z"
  },
  {
    "id": "gt-34",
    "governorate": "كربلاء",
    "course_name": "منهج إدارة المشاريع الاحترافية",
    "domain": "قيادية",
    "course_hours": 12,
    "track": "المسار الثالث",
    "nominees_count": 5,
    "planned_start_date": "2026-04-21",
    "planned_end_date": "2026-04-26",
    "actual_start_date": null,
    "actual_end_date": null,
    "status": "planned",
    "compliance": "delayed",
    "notes": "تأخر يوم بسبب ظروف الطقس",
    "created_by": "emp-4",
    "created_at": "2026-03-01T08:00:00Z",
    "updated_at": "2026-04-15T08:00:00Z"
  },
  {
    "id": "gt-35",
    "governorate": "المثنى",
    "course_name": "منهج أخلاقيات العمل الوظيفي",
    "domain": "قيادية",
    "course_hours": 16,
    "track": "المسار الثالث",
    "nominees_count": 5,
    "planned_start_date": "2026-03-22",
    "planned_end_date": "2026-03-27",
    "actual_start_date": "2026-03-13",
    "actual_end_date": "2026-03-18",
    "status": "completed",
    "compliance": "completed",
    "notes": "",
    "created_by": "emp-3",
    "created_at": "2026-03-01T08:00:00Z",
    "updated_at": "2026-04-15T08:00:00Z"
  },
  {
    "id": "gt-36",
    "governorate": "المثنى",
    "course_name": "منهج الأمن السيبراني المتقدم",
    "domain": "إدارية",
    "course_hours": 16,
    "track": "المسار الأول",
    "nominees_count": 5,
    "planned_start_date": "2026-04-22",
    "planned_end_date": "2026-04-27",
    "actual_start_date": "2026-04-22",
    "actual_end_date": "2026-04-27",
    "status": "completed",
    "compliance": "on_track",
    "notes": "",
    "created_by": "emp-4",
    "created_at": "2026-03-01T08:00:00Z",
    "updated_at": "2026-04-15T08:00:00Z"
  }
];
export const SEED_FOLLOWUP_RECORDS: FollowUpRecord[] = [
  {
    "id": "fur-1",
    "governorate_training_id": "gt-1",
    "governorate": "بغداد",
    "course_name": "منهج إدارة المشاريع الاحترافية",
    "record_date": "2026-05-10",
    "compliance_status": "delayed",
    "notes": "تأخر بسبب عطلة",
    "recorded_by": "emp-3",
    "recorded_by_name": "خالد عبدالله السعيد",
    "created_at": "2026-05-10T08:00:00Z"
  },
  {
    "id": "fur-2",
    "governorate_training_id": "gt-3",
    "governorate": "البصرة",
    "course_name": "منهج الأمن السيبراني المتقدم",
    "record_date": "2026-05-11",
    "compliance_status": "on_track",
    "notes": "سير طبيعي",
    "recorded_by": "emp-14",
    "recorded_by_name": "أمل ناصر الجبوري",
    "created_at": "2026-05-11T08:00:00Z"
  },
  {
    "id": "fur-3",
    "governorate_training_id": "gt-5",
    "governorate": "نينوى",
    "course_name": "منهج تحليل البيانات وذكاء الأعمال",
    "record_date": "2026-05-12",
    "compliance_status": "on_track",
    "notes": "سير طبيعي",
    "recorded_by": "emp-3",
    "recorded_by_name": "خالد عبدالله السعيد",
    "created_at": "2026-05-12T08:00:00Z"
  },
  {
    "id": "fur-4",
    "governorate_training_id": "gt-7",
    "governorate": "ذي قار",
    "course_name": "منهج مهارات التواصل المؤسسي",
    "record_date": "2026-05-13",
    "compliance_status": "delayed",
    "notes": "تأخر بسبب عطلة",
    "recorded_by": "emp-14",
    "recorded_by_name": "أمل ناصر الجبوري",
    "created_at": "2026-05-13T08:00:00Z"
  },
  {
    "id": "fur-5",
    "governorate_training_id": "gt-9",
    "governorate": "السليمانية",
    "course_name": "منهج الإدارة الإلكترونية / Office",
    "record_date": "2026-05-14",
    "compliance_status": "on_track",
    "notes": "سير طبيعي",
    "recorded_by": "emp-3",
    "recorded_by_name": "خالد عبدالله السعيد",
    "created_at": "2026-05-14T08:00:00Z"
  },
  {
    "id": "fur-6",
    "governorate_training_id": "gt-11",
    "governorate": "بابل",
    "course_name": "منهج أخلاقيات العمل الوظيفي",
    "record_date": "2026-05-15",
    "compliance_status": "on_track",
    "notes": "سير طبيعي",
    "recorded_by": "emp-14",
    "recorded_by_name": "أمل ناصر الجبوري",
    "created_at": "2026-05-15T08:00:00Z"
  },
  {
    "id": "fur-7",
    "governorate_training_id": "gt-13",
    "governorate": "ديالى",
    "course_name": "منهج إدارة المشاريع الاحترافية",
    "record_date": "2026-05-16",
    "compliance_status": "delayed",
    "notes": "تأخر بسبب عطلة",
    "recorded_by": "emp-3",
    "recorded_by_name": "خالد عبدالله السعيد",
    "created_at": "2026-05-16T08:00:00Z"
  },
  {
    "id": "fur-8",
    "governorate_training_id": "gt-15",
    "governorate": "الأنبار",
    "course_name": "منهج الأمن السيبراني المتقدم",
    "record_date": "2026-05-17",
    "compliance_status": "on_track",
    "notes": "سير طبيعي",
    "recorded_by": "emp-14",
    "recorded_by_name": "أمل ناصر الجبوري",
    "created_at": "2026-05-17T08:00:00Z"
  }
];
export const SEED_FOLLOWUP_NOTIFS: FollowUpNotification[] = [
  {
    "id": "fun-1",
    "governorate": "بغداد",
    "assigned_to": "emp-3",
    "assigned_to_name": "خالد عبدالله السعيد",
    "assigned_by": "emp-1",
    "assigned_by_name": "أحمد محمد العلي",
    "frequency": "weekly",
    "active": true,
    "notes": "متابعة دورية لمحافظة بغداد",
    "created_at": "2026-04-01T08:00:00Z"
  },
  {
    "id": "fun-2",
    "governorate": "البصرة",
    "assigned_to": "emp-14",
    "assigned_to_name": "أمل ناصر الجبوري",
    "assigned_by": "emp-1",
    "assigned_by_name": "أحمد محمد العلي",
    "frequency": "biweekly",
    "active": true,
    "notes": "متابعة دورية لمحافظة البصرة",
    "created_at": "2026-04-01T08:00:00Z"
  },
  {
    "id": "fun-3",
    "governorate": "نينوى",
    "assigned_to": "emp-3",
    "assigned_to_name": "خالد عبدالله السعيد",
    "assigned_by": "emp-1",
    "assigned_by_name": "أحمد محمد العلي",
    "frequency": "monthly",
    "active": true,
    "notes": "متابعة دورية لمحافظة نينوى",
    "created_at": "2026-04-01T08:00:00Z"
  },
  {
    "id": "fun-4",
    "governorate": "ذي قار",
    "assigned_to": "emp-14",
    "assigned_to_name": "أمل ناصر الجبوري",
    "assigned_by": "emp-1",
    "assigned_by_name": "أحمد محمد العلي",
    "frequency": "weekly",
    "active": true,
    "notes": "متابعة دورية لمحافظة ذي قار",
    "created_at": "2026-04-01T08:00:00Z"
  },
  {
    "id": "fun-5",
    "governorate": "السليمانية",
    "assigned_to": "emp-3",
    "assigned_to_name": "خالد عبدالله السعيد",
    "assigned_by": "emp-1",
    "assigned_by_name": "أحمد محمد العلي",
    "frequency": "biweekly",
    "active": true,
    "notes": "متابعة دورية لمحافظة السليمانية",
    "created_at": "2026-04-01T08:00:00Z"
  },
  {
    "id": "fun-6",
    "governorate": "بابل",
    "assigned_to": "emp-14",
    "assigned_to_name": "أمل ناصر الجبوري",
    "assigned_by": "emp-1",
    "assigned_by_name": "أحمد محمد العلي",
    "frequency": "monthly",
    "active": true,
    "notes": "متابعة دورية لمحافظة بابل",
    "created_at": "2026-04-01T08:00:00Z"
  }
];
export const SEED_NOTIFICATIONS: Notification[] = [
  {
    "id": "notif-1",
    "user_id": null,
    "message": "دورة 'خدمة العملاء المتميزة' جارية الآن",
    "type": "info",
    "is_read": false,
    "date": "2026-05-15",
    "created_at": "2026-05-15T08:00:00Z",
    "link": "/courses?focus=crs-5"
  },
  {
    "id": "notif-2",
    "user_id": "emp-1",
    "message": "3 طلبات إجازة بانتظار اعتمادك",
    "type": "warning",
    "is_read": false,
    "date": "2026-05-19",
    "created_at": "2026-05-19T08:00:00Z",
    "link": "/hr"
  },
  {
    "id": "notif-3",
    "user_id": "emp-2",
    "message": "5 طلبات إجازة تحتاج موافقة مدير القسم",
    "type": "info",
    "is_read": false,
    "date": "2026-05-19",
    "created_at": "2026-05-19T08:00:00Z",
    "link": "/hr"
  },
  {
    "id": "notif-4",
    "user_id": "emp-10",
    "message": "تم تكليفك بمهمة جديدة: تحديث منهج القيادة",
    "type": "info",
    "is_read": false,
    "date": "2026-05-10",
    "created_at": "2026-05-10T08:00:00Z",
    "link": "/tasks?focus=tsk-3"
  },
  {
    "id": "notif-5",
    "user_id": null,
    "message": "منهج 'الأمن السيبراني' في مرحلة التدقيق",
    "type": "info",
    "is_read": false,
    "date": "2026-05-12",
    "created_at": "2026-05-12T08:00:00Z",
    "link": "/curriculum?focus=cur-2"
  },
  {
    "id": "notif-6",
    "user_id": "emp-3",
    "message": "متابعة بغداد: متأخر — دورة الإدارة الإلكترونية",
    "type": "warning",
    "is_read": false,
    "date": "2026-05-16",
    "created_at": "2026-05-16T08:00:00Z",
    "link": "/training-plan"
  }
];
export const SEED_AUDIT_LOG: AuditEntry[] = [
  {
    "id": "aud-1",
    "user_name": "أحمد محمد العلي",
    "action": "إنشاء دورة",
    "target": "دورة Office الاحترافية",
    "timestamp": "2026-05-10T08:00:00Z"
  },
  {
    "id": "aud-2",
    "user_name": "نورة سعد المالكي",
    "action": "تحديث منهج",
    "target": "منهج تحليل البيانات",
    "timestamp": "2026-05-12T08:00:00Z"
  },
  {
    "id": "aud-3",
    "user_name": "خالد عبدالله السعيد",
    "action": "الموافقة على إجازة",
    "target": "طلب إجازة - زينب الموسوي",
    "timestamp": "2026-05-14T08:00:00Z"
  },
  {
    "id": "aud-4",
    "user_name": "عبدالرحمن فهد الشمري",
    "action": "أرشفة كتاب",
    "target": "و/2026/030 - كتاب شكر للمتدربين",
    "timestamp": "2026-05-13T08:00:00Z"
  },
  {
    "id": "aud-5",
    "user_name": "فاطمة حسن الأمير",
    "action": "الموافقة النهائية",
    "target": "طلب إجازة - علي الخفاجي",
    "timestamp": "2026-05-15T08:00:00Z"
  }
];
export const SEED_WEEK_SCHEDULES: WeekScheduleEntry[] = [
  {
    "id": "ws-1-1",
    "governorate": "بغداد",
    "week": 1,
    "start_date": "2026-03-01",
    "end_date": "2026-03-07",
    "label": "الأسبوع 1"
  },
  {
    "id": "ws-1-2",
    "governorate": "بغداد",
    "week": 2,
    "start_date": "2026-03-15",
    "end_date": "2026-03-21",
    "label": "الأسبوع 2"
  },
  {
    "id": "ws-1-3",
    "governorate": "بغداد",
    "week": 3,
    "start_date": "2026-04-01",
    "end_date": "2026-04-07",
    "label": "الأسبوع 3"
  },
  {
    "id": "ws-2-1",
    "governorate": "البصرة",
    "week": 1,
    "start_date": "2026-03-01",
    "end_date": "2026-03-07",
    "label": "الأسبوع 1"
  },
  {
    "id": "ws-2-2",
    "governorate": "البصرة",
    "week": 2,
    "start_date": "2026-03-15",
    "end_date": "2026-03-21",
    "label": "الأسبوع 2"
  },
  {
    "id": "ws-2-3",
    "governorate": "البصرة",
    "week": 3,
    "start_date": "2026-04-01",
    "end_date": "2026-04-07",
    "label": "الأسبوع 3"
  },
  {
    "id": "ws-3-1",
    "governorate": "نينوى",
    "week": 1,
    "start_date": "2026-03-01",
    "end_date": "2026-03-07",
    "label": "الأسبوع 1"
  },
  {
    "id": "ws-3-2",
    "governorate": "نينوى",
    "week": 2,
    "start_date": "2026-03-15",
    "end_date": "2026-03-21",
    "label": "الأسبوع 2"
  },
  {
    "id": "ws-3-3",
    "governorate": "نينوى",
    "week": 3,
    "start_date": "2026-04-01",
    "end_date": "2026-04-07",
    "label": "الأسبوع 3"
  },
  {
    "id": "ws-4-1",
    "governorate": "ذي قار",
    "week": 1,
    "start_date": "2026-03-01",
    "end_date": "2026-03-07",
    "label": "الأسبوع 1"
  },
  {
    "id": "ws-4-2",
    "governorate": "ذي قار",
    "week": 2,
    "start_date": "2026-03-15",
    "end_date": "2026-03-21",
    "label": "الأسبوع 2"
  },
  {
    "id": "ws-4-3",
    "governorate": "ذي قار",
    "week": 3,
    "start_date": "2026-04-01",
    "end_date": "2026-04-07",
    "label": "الأسبوع 3"
  },
  {
    "id": "ws-5-1",
    "governorate": "السليمانية",
    "week": 1,
    "start_date": "2026-03-01",
    "end_date": "2026-03-07",
    "label": "الأسبوع 1"
  },
  {
    "id": "ws-5-2",
    "governorate": "السليمانية",
    "week": 2,
    "start_date": "2026-03-15",
    "end_date": "2026-03-21",
    "label": "الأسبوع 2"
  },
  {
    "id": "ws-5-3",
    "governorate": "السليمانية",
    "week": 3,
    "start_date": "2026-04-01",
    "end_date": "2026-04-07",
    "label": "الأسبوع 3"
  },
  {
    "id": "ws-6-1",
    "governorate": "بابل",
    "week": 1,
    "start_date": "2026-03-01",
    "end_date": "2026-03-07",
    "label": "الأسبوع 1"
  },
  {
    "id": "ws-6-2",
    "governorate": "بابل",
    "week": 2,
    "start_date": "2026-03-15",
    "end_date": "2026-03-21",
    "label": "الأسبوع 2"
  },
  {
    "id": "ws-6-3",
    "governorate": "بابل",
    "week": 3,
    "start_date": "2026-04-01",
    "end_date": "2026-04-07",
    "label": "الأسبوع 3"
  },
  {
    "id": "ws-7-1",
    "governorate": "ديالى",
    "week": 1,
    "start_date": "2026-03-01",
    "end_date": "2026-03-07",
    "label": "الأسبوع 1"
  },
  {
    "id": "ws-7-2",
    "governorate": "ديالى",
    "week": 2,
    "start_date": "2026-03-15",
    "end_date": "2026-03-21",
    "label": "الأسبوع 2"
  },
  {
    "id": "ws-7-3",
    "governorate": "ديالى",
    "week": 3,
    "start_date": "2026-04-01",
    "end_date": "2026-04-07",
    "label": "الأسبوع 3"
  },
  {
    "id": "ws-8-1",
    "governorate": "الأنبار",
    "week": 1,
    "start_date": "2026-03-01",
    "end_date": "2026-03-07",
    "label": "الأسبوع 1"
  },
  {
    "id": "ws-8-2",
    "governorate": "الأنبار",
    "week": 2,
    "start_date": "2026-03-15",
    "end_date": "2026-03-21",
    "label": "الأسبوع 2"
  },
  {
    "id": "ws-8-3",
    "governorate": "الأنبار",
    "week": 3,
    "start_date": "2026-04-01",
    "end_date": "2026-04-07",
    "label": "الأسبوع 3"
  },
  {
    "id": "ws-9-1",
    "governorate": "كركوك",
    "week": 1,
    "start_date": "2026-03-01",
    "end_date": "2026-03-07",
    "label": "الأسبوع 1"
  },
  {
    "id": "ws-9-2",
    "governorate": "كركوك",
    "week": 2,
    "start_date": "2026-03-15",
    "end_date": "2026-03-21",
    "label": "الأسبوع 2"
  },
  {
    "id": "ws-9-3",
    "governorate": "كركوك",
    "week": 3,
    "start_date": "2026-04-01",
    "end_date": "2026-04-07",
    "label": "الأسبوع 3"
  },
  {
    "id": "ws-10-1",
    "governorate": "واسط",
    "week": 1,
    "start_date": "2026-03-01",
    "end_date": "2026-03-07",
    "label": "الأسبوع 1"
  },
  {
    "id": "ws-10-2",
    "governorate": "واسط",
    "week": 2,
    "start_date": "2026-03-15",
    "end_date": "2026-03-21",
    "label": "الأسبوع 2"
  },
  {
    "id": "ws-10-3",
    "governorate": "واسط",
    "week": 3,
    "start_date": "2026-04-01",
    "end_date": "2026-04-07",
    "label": "الأسبوع 3"
  },
  {
    "id": "ws-11-1",
    "governorate": "صلاح الدين",
    "week": 1,
    "start_date": "2026-03-01",
    "end_date": "2026-03-07",
    "label": "الأسبوع 1"
  },
  {
    "id": "ws-11-2",
    "governorate": "صلاح الدين",
    "week": 2,
    "start_date": "2026-03-15",
    "end_date": "2026-03-21",
    "label": "الأسبوع 2"
  },
  {
    "id": "ws-11-3",
    "governorate": "صلاح الدين",
    "week": 3,
    "start_date": "2026-04-01",
    "end_date": "2026-04-07",
    "label": "الأسبوع 3"
  },
  {
    "id": "ws-12-1",
    "governorate": "النجف",
    "week": 1,
    "start_date": "2026-03-01",
    "end_date": "2026-03-07",
    "label": "الأسبوع 1"
  },
  {
    "id": "ws-12-2",
    "governorate": "النجف",
    "week": 2,
    "start_date": "2026-03-15",
    "end_date": "2026-03-21",
    "label": "الأسبوع 2"
  },
  {
    "id": "ws-12-3",
    "governorate": "النجف",
    "week": 3,
    "start_date": "2026-04-01",
    "end_date": "2026-04-07",
    "label": "الأسبوع 3"
  },
  {
    "id": "ws-13-1",
    "governorate": "القادسية",
    "week": 1,
    "start_date": "2026-03-01",
    "end_date": "2026-03-07",
    "label": "الأسبوع 1"
  },
  {
    "id": "ws-13-2",
    "governorate": "القادسية",
    "week": 2,
    "start_date": "2026-03-15",
    "end_date": "2026-03-21",
    "label": "الأسبوع 2"
  },
  {
    "id": "ws-13-3",
    "governorate": "القادسية",
    "week": 3,
    "start_date": "2026-04-01",
    "end_date": "2026-04-07",
    "label": "الأسبوع 3"
  },
  {
    "id": "ws-14-1",
    "governorate": "ميسان",
    "week": 1,
    "start_date": "2026-03-01",
    "end_date": "2026-03-07",
    "label": "الأسبوع 1"
  },
  {
    "id": "ws-14-2",
    "governorate": "ميسان",
    "week": 2,
    "start_date": "2026-03-15",
    "end_date": "2026-03-21",
    "label": "الأسبوع 2"
  },
  {
    "id": "ws-14-3",
    "governorate": "ميسان",
    "week": 3,
    "start_date": "2026-04-01",
    "end_date": "2026-04-07",
    "label": "الأسبوع 3"
  },
  {
    "id": "ws-15-1",
    "governorate": "أربيل",
    "week": 1,
    "start_date": "2026-03-01",
    "end_date": "2026-03-07",
    "label": "الأسبوع 1"
  },
  {
    "id": "ws-15-2",
    "governorate": "أربيل",
    "week": 2,
    "start_date": "2026-03-15",
    "end_date": "2026-03-21",
    "label": "الأسبوع 2"
  },
  {
    "id": "ws-15-3",
    "governorate": "أربيل",
    "week": 3,
    "start_date": "2026-04-01",
    "end_date": "2026-04-07",
    "label": "الأسبوع 3"
  },
  {
    "id": "ws-16-1",
    "governorate": "دهوك",
    "week": 1,
    "start_date": "2026-03-01",
    "end_date": "2026-03-07",
    "label": "الأسبوع 1"
  },
  {
    "id": "ws-16-2",
    "governorate": "دهوك",
    "week": 2,
    "start_date": "2026-03-15",
    "end_date": "2026-03-21",
    "label": "الأسبوع 2"
  },
  {
    "id": "ws-16-3",
    "governorate": "دهوك",
    "week": 3,
    "start_date": "2026-04-01",
    "end_date": "2026-04-07",
    "label": "الأسبوع 3"
  },
  {
    "id": "ws-17-1",
    "governorate": "كربلاء",
    "week": 1,
    "start_date": "2026-03-01",
    "end_date": "2026-03-07",
    "label": "الأسبوع 1"
  },
  {
    "id": "ws-17-2",
    "governorate": "كربلاء",
    "week": 2,
    "start_date": "2026-03-15",
    "end_date": "2026-03-21",
    "label": "الأسبوع 2"
  },
  {
    "id": "ws-17-3",
    "governorate": "كربلاء",
    "week": 3,
    "start_date": "2026-04-01",
    "end_date": "2026-04-07",
    "label": "الأسبوع 3"
  },
  {
    "id": "ws-18-1",
    "governorate": "المثنى",
    "week": 1,
    "start_date": "2026-03-01",
    "end_date": "2026-03-07",
    "label": "الأسبوع 1"
  },
  {
    "id": "ws-18-2",
    "governorate": "المثنى",
    "week": 2,
    "start_date": "2026-03-15",
    "end_date": "2026-03-21",
    "label": "الأسبوع 2"
  },
  {
    "id": "ws-18-3",
    "governorate": "المثنى",
    "week": 3,
    "start_date": "2026-04-01",
    "end_date": "2026-04-07",
    "label": "الأسبوع 3"
  }
];
